### ISSUE TITLE
fatal error: wiringPi.h: No such file or directory

### ISSUE THREAD

**Issue by aep** [matrix-io/xc3sprog#24] opened 2020-11-06 14:49 UTC
master doesn't compile out of the box. google leads me to believe this is

http://wiringpi.com/ ?

but the readme doesnt mention that, and i'm super confused why this project is related to raspberry pi at all.

**Comment by zackpi** [comment] 2020-11-14 14:42
having the same issue. Did you have any luck after adding wiringPi.h?

**Comment by zackpi** [comment] 2020-11-14 14:50
seems like wiringPi is no longer officially supported. I'm beginning to think that xc3sprog is not either, since it seems to use several deprecated systems. Is there an alternative open-source project for programming Arty 7 boards?

**Comment by aep** [comment] 2020-12-02 09:53
nop, openocd works fine for me fwiw

**Comment by pcwwgkg** [comment] 2021-03-07 05:00
I don't think they are still maintaining this project. There are two existing PRs trying to resolve this. I can confirm they work.

**Comment by AlieGG** [comment] 2021-03-16 19:43
@pcwwgkg Thanks for pointing that out to us. I'm having our engineers test the PRs so we can merge them.

**Comment by AlieGG** [comment] 2021-03-16 20:04
Ok we have merged this PR which gets around wiringpi. https://github.com/matrix-io/xc3sprog/pull/20

**Closed as completed by AlieGG** 2021-03-16 20:04 UTC
